import {ceramica,catadevinos,catasdecervezas,maquillajeymerienda,tarotyvino,tarotymerienda,personalizado} from "@/assets/Images";
import {ceramica1,catadevinos1,catasdecervezas1,maquillajeymerienda1,tarotyvino1,tarotymerienda1,juan} from "@/assets/Images";
import {ceramica2,catadevinos2,catasdecervezas2,carlos,tarotyvino22,tarotymerienda22,personalizado2} from "@/assets/Images"


export const eventos = [
  {
    nombre: "Cata de vinos",
    slug: "cata-de-vinos",
    descripcion: "Disfrutá de una selección exclusiva de vinos.",
    explicacion: "Embarcate en un viaje sensorial único con nuestra cata de vinos. En cada copa, vas a descubrir una historia que se cuenta a través de aromas y sabores. \n\nGuiado por un sommelier experto, aprenderás sobre los orígenes de cada vino, los matices que los hacen únicos y cómo combinarlos para una experiencia completa. Desde tintos intensos hasta blancos refrescantes, hay algo especial para cada paladar. \n\nEs el momento perfecto para relajarte, disfrutar de buena compañía y aprender un poco más sobre el fascinante mundo del vino.",
    precio: "25,000",
    duracion: "1h 30m",
    material: "Vinos de alta calidad",
    src: catadevinos,
    srcExtra: [catadevinos1, catadevinos2],
    ubicacion: "Ramos Mejía",
  },
  {
    nombre: "Cata de cerveza",
    slug: "cata-de-cerveza",
    descripcion: "Explorá una variedad de cervezas artesanales.",
    explicacion: "Adentrate en el mundo de la cerveza artesanal en una experiencia única. Vas a aprender sobre los diferentes estilos y los secretos detrás de cada proceso de elaboración. \n\nDe la mano de un maestro cervecero apasionado, vas a degustar variedades locales e internacionales. Cada cerveza tiene algo para contar: desde sus aromas hasta los sabores que la hacen especial. \n\nEs el plan ideal para compartir con amigos, relajarte y descubrir nuevos sabores.",
    precio: "25,000",
    duracion: "1h 30m",
    material: "Cervezas artesanales",
    src: catasdecervezas,
    srcExtra: [catasdecervezas1, catasdecervezas2],
    ubicacion: "Ramos Mejía",
  },
  {
    nombre: "Cerámica",
    slug: "ceramica",
    descripcion: "Animate a crear piezas únicas de cerámica artesanal.",
    explicacion: "Descubrí el arte de la cerámica en un taller pensado para que liberes tu creatividad. Aprendé las técnicas básicas para trabajar con arcilla, desde la preparación hasta la creación de tus propias piezas. \n\nGuiado por expertos, vas a explorar distintas formas y estilos mientras te conectás con tu lado artístico. Este espacio es perfecto para expresarte en un ambiente relajado y acogedor. \n\nAl final, no solo te vas a llevar tus creaciones, sino también nuevos conocimientos y habilidades en este hermoso arte.",
    precio: "25,000",
    duracion: "1h 30m",
    material: "Arcilla y herramientas",
    src: ceramica,
    srcExtra: [ceramica1, ceramica2],
    ubicacion: "Ramos Mejía",
  },
  {
    nombre: "Maquillaje y merienda",
    slug: "maquillaje-y-merienda",
    descripcion: "Aprendé técnicas de maquillaje mientras disfrutás de una rica merienda.",
    explicacion: "Sumate a este taller de maquillaje donde vas a aprender trucos y secretos para realzar tu belleza. Todo esto mientras disfrutás de una merienda deliciosa en un ambiente relajado y ameno. \n\nDurante la actividad, un profesional te guiará paso a paso, enseñándote técnicas útiles para tu día a día o para ocasiones especiales. Se cubrirán temas como cuidado de la piel, elección de colores y aplicaciones prácticas. \n\nEs una experiencia ideal para mejorar tus habilidades y pasar un buen rato en buena compañía.",
    precio: "25,000",
    duracion: "1h 30m",
    material: "Maquillaje y productos de belleza",
    src: maquillajeymerienda,
    srcExtra: [maquillajeymerienda1, carlos],
    ubicacion: "Ramos Mejía",
  },
  {
    nombre: "Tarot y vino",
    slug: "tarot-y-vino",
    descripcion: "Conocé tu futuro mientras disfrutás de una copa de vino.",
    explicacion: "Viví una experiencia mística con una lectura de tarot acompañada de una copa de vino. En un ambiente íntimo, un tarotista profesional te guiará a través de las cartas, ofreciéndote reflexiones y respuestas a tus preguntas. \n\nMientras degustás vinos especialmente seleccionados, vas a tener la oportunidad de conectar con tus emociones y explorar tu futuro. \n\nEs el momento perfecto para reflexionar y disfrutar de una experiencia sensorial que combina sabores y autoconocimiento.",
    precio: "25,000",
    duracion: "1h 30m",
    material: "Tarot y vinos seleccionados",
    src: tarotyvino,
    srcExtra: [tarotyvino1, tarotyvino22],
    ubicacion: "Ramos Mejía",
  },
  {
    nombre: "Tarot y merienda",
    slug: "tarot-y-merienda",
    descripcion: "Disfrutá de una tarde relajante con tarot y merienda.",
    explicacion: "Dejate llevar por la magia de las cartas en una tarde única que combina introspección y sabores deliciosos. Una tarotista profesional te acompañará en un espacio pensado para reflexionar y explorar tus inquietudes. \n\nMientras tanto, disfrutarás de una merienda especialmente preparada para complementar la experiencia. Es la oportunidad perfecta para compartir con amigos o regalarte un momento personal en un entorno cálido y acogedor.",
    precio: "25,000",
    duracion: "1h 30m",
    material: "Tarot y merienda",
    src: tarotymerienda,
    srcExtra: [tarotymerienda1, tarotymerienda22],
    ubicacion: "Ramos Mejía",
  },
  {
    nombre: "Personalizado",
    slug: "personalizado",
    descripcion: "Diseñá un evento único para vos y tus amigos.",
    explicacion: "Hacemos realidad el evento que tenés en mente. Desde el catering hasta la ambientación, nos ocupamos de cada detalle para que tu experiencia sea inolvidable. \n\nNuestro equipo te ayudará a diseñar una propuesta a medida, pensada exclusivamente para vos y tus invitados. Ya sea un encuentro íntimo o una celebración especial, estamos acá para asegurarnos de que todo salga perfecto. \n\nConsultanos y empecemos a planear tu evento ideal.",
    precio: "25,000",
    duracion: "1h 30m",
    material: "Variable",
    src: personalizado,
    srcExtra: [juan, personalizado2],
    ubicacion: "Ramos Mejía",
  },
];


  